#!/usr/bin/expect --

;# Demands 5 Input parameters
;# username_client, password_client, ip_client

set timeout 15

set user_name [lindex $argv 0]
set password [lindex $argv 1]
set ip_ [lindex $argv 2]

set file_path [lindex $argv 3]

set destination_path [lindex $argv 4]


spawn scp -r $file_path $user_name@$ip_:$destination_path
sleep 1
expect "password:"
send "$password\r"
sleep 1
expect "$"
close
